### ISSUE TITLE
Error Syntax

### ISSUE THREAD

**Issue by Souttz** [aie1123/CS2-No-Recoil-LOGITECH-Script-Macro#2]
I imported the data from the .lua file, but this error occurs > SYNTAX_ERROR Line Number:1609

**Comment by Souttz** [comment]
![image](https://github.com/aie1123/CS2-CSGO-No-Recoil-LOGITECH-Script-Macro/assets/32117451/eff84583-88c5-49a5-ab8d-51823263b653)

I fixed the error! Line 116 does not contain the initial "zz" for the script command, so it does not work. I hope I helped someone in the future!

**Comment by aie1123** [comment]
fixed
