### ISSUE TITLE
Key

### ISSUE THREAD

**Issue by Kesls** [aie1123/CS2-No-Recoil-LOGITECH-Script-Macro#5]
Hello friend, I have some doubts about using and changing the key, how it works, as I have already tested it in different ways and I still haven't been able to get the recoil to be used for another weapon.

**Comment by aie1123** [comment]
The key setting is the set mouse side button

**Comment by Kesls** [comment]
Yes, I understood that, I couldn't really understand the configuration change related to each weapon, would it just be pressing the numeric buttons?

**Comment by Kesls** [comment]
I understand that Alt causes the script to not be used at the moment, but I was unable to make the weapon settings change

**Comment by aie1123** [comment]
You can assign side mouse buttons to specific weapons, for example: single click of side mouse button 5: M4A1, double click of side mouse button 5: M4A4, hold down Ctrl key and click side mouse button 5: AUG. - Translated by Google

**Comment by Kesls** [comment]
But are these the current settings or would I have to configure them?
This is my doubt about which keys are current

**Comment by Kesls** [comment]
If it's not too much to ask, I would like you to explain how to use the script during games because I'm confused, I spent the night trying to get results, but all the ways I tried still had the same recoil pattern

**Comment by Kesls** [comment]
Hello friend, I understand that the configuration change is done using the two side buttons of the mouse, however how do I change between let's say AK and galil or M, as far as I understand so far 1 button goes to AK and the other goes to M4, until the I haven't been able to switch to other weapons at the moment, could you help me?

**Comment by massivez0r** [comment]
The same question, please tell us author
